spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env : blue

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://gunryul.store/login/oauth2/code/google"
server:
  port: 8080
  serverAddress: 15.164.125.231

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://gunryul.store/login/oauth2/code/google"

server:
  port: 8081
  serverAddress: 15.164.125.231

serverName: green_server

---
#############################################
### Server Properties #######################
#############################################
# server:
#   port: 8080
  # ssl:
  #   key-store: classpath:secure/localhost.p12
  #   key-store-type: PKCS12
  #   key-store-password: changeit

#############################################
### Mail Properties #########################
#############################################
spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#############################################
### DB Properties ###########################
#############################################


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

#############################################
### OAuth Properties ###########################
#############################################
  config:
      activate:
        on-profile: common
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 420736999131-kj81irgmjv9d4o9mg7hb5e74gbgqqif4.apps.googleusercontent.com
            scope: profile, email
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
    
#############################################
### Multipart Properties ####################
#############################################

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#############################################
### Password properties #####################
#############################################
#Password won't be able to recover after 30 minutes

password-recovery:
  deadline-ms: 1800000

#############################################
### Cookie Properties #######################
#############################################

refresh-cookie:
  name: refreshToken
  expire-time: 2419200

#############################################
### Image Storage Properties ################
#############################################

image:
  location: ./uploads

#############################################
### News Properties #########################
#############################################
news:
  page-number: 6


#############################################
### Article Properties #########################
#############################################
article:
  page-number: 6

#############################################
### Training Properties #####################
#############################################
training:
  max-users-perGroup: 20


#############################################
### Crawling Properties #####################
#############################################
url:
  surfing-url: https://www.google.com/search?sca_esv=825112d354c86d94&q=%EC%84%9C%ED%95%91&tbm=nws&source=lnms&prmd=ivnsmbz&sa=X&ved=2ahUKEwjk0om0gtCGAxWts1YBHWP-IR8Q0pQJegQIDxAB&biw=1920&bih=991&dpr=1
  snowboarding-url: https://www.google.com/search?q=%EC%8A%A4%EB%85%B8%EC%9A%B0%EB%B3%B4%EB%93%9C&sca_esv=825112d354c86d94&biw=1920&bih=991&tbm=nws&ei=7mhmZtahMLDl2roP1L6A8Ag&udm=&ved=0ahUKEwjW0Ja1gtCGAxWwslYBHVQfAI4Q4dUDCA0&uact=5&oq=%EC%8A%A4%EB%85%B8%EC%9A%B0%EB%B3%B4%EB%93%9C&gs_lp=Egxnd3Mtd2l6LW5ld3MiD-yKpOuFuOyasOuztOuTnDILEAAYgAQYsQMYgwEyCxAAGIAEGLEDGIMBMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARIuBNQAFiOEnAKeACQAQSYAWugAakKqgEEMTAuNLgBA8gBAPgBAZgCEaACnwbCAgQQABgDwgIIEAAYgAQYsQPCAg0QABiABBixAxiDARgNwgIHEAAYgAQYDZgDAJIHBDE0LjOgB9pJ&sclient=gws-wiz-news
  skateboarding-url: https://www.google.com/search?q=%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8A%B8%EB%B3%B4%EB%93%9C&sca_esv=825112d354c86d94&biw=1920&bih=991&tbm=nws&ei=-2hmZuPyEcTl2roP7qe7mAM&udm=&ved=0ahUKEwij3JG7gtCGAxXEslYBHe7TDjMQ4dUDCA0&uact=5&oq=%EC%8A%A4%EC%BC%80%EC%9D%B4%ED%8A%B8%EB%B3%B4%EB%93%9C&gs_lp=Egxnd3Mtd2l6LW5ld3MiEuyKpOy8gOydtO2KuOuztOuTnDILEAAYgAQYsQMYgwEyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARIlx9QAFiEHnAIeACQAQSYAXOgAbYNqgEEMTMuNbgBA8gBAPgBAZgCFKACmAnCAgQQABgDwgIIEAAYgAQYsQPCAgoQABiABBhDGIoFwgIHEAAYgAQYDZgDAJIHBDE2LjSgB55n&sclient=gws-wiz-news